import mongoose from 'mongoose';

const fullScheduleEventSchema = new mongoose.Schema({ id: mongoose.Schema.Types.Mixed, day: String, title: String, time: String, category: String, location: String, desc: String }, { _id: false });
const eventSchema = new mongoose.Schema({ id: mongoose.Schema.Types.Mixed, title: String, time: String, desc: String }, { _id: false });
const bigScreenVideoSchema = new mongoose.Schema({ id: mongoose.Schema.Types.Mixed, title: String, url: String }, { _id: false });
const galleryItemSchema = new mongoose.Schema({ id: mongoose.Schema.Types.Mixed, title: String, year: String, type: String, url: String }, { _id: false });
const reelSchema = new mongoose.Schema({
  id: mongoose.Schema.Types.Mixed,
  title: String,
  username: String,
  authorDisplayText: String,
  isVerified: Boolean,
  coauthorVerified: Boolean,
  subtitleTag: String,
  secondaryAvatarUrl: String,
  audioText: String,
  likesCount: String,
  commentsCount: String,
  sharesCount: String,
  repostsCount: String,
  rawLikes: Number,
  avatarUrl: String,
  posterUrl: String,
  likes: String,
  views: String,
  url: String,
  videoUrl: String,
  embedUrl: String,
  shortcode: String
}, { _id: false });

const siteDataSchema = new mongoose.Schema({
  key: { type: String, default: 'main', unique: true },
  adminPassword: { type: String, default: 'yuva2026' },
  heroHeading: String,
  targetDateStr: String,
  aagmanDate: { type: String, default: '2026-09-12' },
  festivalStartDate: { type: String, default: '2026-09-14' },
  visarjanDate: { type: String, default: '2026-09-25' },
  simulatedDay: { type: String, default: 'auto' },
  heroTagline: String,
  bannerMediaType: { type: String, default: 'photo' },
  bannerImageUrl: String,
  bannerVideoUrl: String,
  bannerTextAlignment: { type: String, default: 'left' },
  bannerVideoSound: { type: String, default: 'off' },
  videoUrl: String,
  bigScreenVideos: [bigScreenVideoSchema],
  mandalLogoUrl: String,
  aboutText: String,
  yearsCount: String,
  volunteersCount: String,
  devoteesCount: String,
  fullScheduleHeader: String,
  fullScheduleSubText: String,
  heroHeadingLines: [String],
  heroHeadingHighlightLine: String,
  mandalLocation: String,
  bigScreenHeaderTitle: String,
  reelsHeaderTitle: String,
  reelsHeaderSubText: String,
  reelsInstaHandle: String,
  reelsInstaUrl: String,
  reviewsBadge: String,
  reviewsTitle: String,
  reviewsSub: String,
  footerMandalTitle: String,
  footerMandalTagline: String,
  footerAddressHeading: String,
  footerAddressText: String,
  footerInstaUrl: String,
  footerInstaText: String,
  footerMapHeading: String,
  footerMapEmbedUrl: String,
  footerGoogleMapsUrl: String,
  footerGoogleMapsBtnText: String,
  footerCopyrightText: String,
  contactInfo: {
    address: String,
    phone1: String,
    phone2: String,
    email: String,
    timings: String,
    headerTitle: String,
    headerSubText: String,
    gmapsUrl: String,
    instaHandle: String,
    instaUrl: String,
    socialDesc: String,
    timingPandalOpen: String,
    timingMorningAarti: String,
    timingEveningAarti: String,
    timingPrasad: String,
    formHeader: String,
    formSubText: String
  },
  volunteers: [mongoose.Schema.Types.Mixed],
  inquiries: [mongoose.Schema.Types.Mixed],
  donations: [mongoose.Schema.Types.Mixed],
  events: [eventSchema],
  scheduleEvents: [fullScheduleEventSchema],
  galleryItems: [galleryItemSchema],
  reels: [reelSchema]
}, { timestamps: true, strict: false });

const SiteData = mongoose.model('SiteData', siteDataSchema);
export default SiteData;
